### ISSUE TITLE
User Login Authentication

### ISSUE THREAD

**Issue by omarchehab98** [Karim94/IIFYM#14]
- [ ] New idea for enhancing Authentication experience (Login Screen)

1. Ideally, the user is prompted for their email. Look up the email in Firebase and get the providers that the email is associated with.
2. If there are no providers, proceed to registration
3. If the provider is email, prompt for password
4. If the provider is google proceed to google authentication
5. If the provider is google and email prompt authentication options

**Comment by Karim94** [comment]
- [ ] in SignInUserPass, check TODO's and update with the following:

1. if(getProvider() != Email), check his providers, and tell him his options
2. else -his provider is email but he typed wrong password-
