### ISSUE TITLE
User Login/Authentication

### ISSUE THREAD

**Issue by Karim94** [Karim94/IIFYM#7]
- [x] Forgot Password button
- [x] Google account

**Comment by omarchehab98** [comment]
# Forgot Password

1. **forgot password** is clicked
2. user is prompted for **email address**
3. user should be sent an email with **single use token** to **reset password**

https://www.firebase.com/docs/web/guide/login/password.html#section-reset-email
this link shows how to reset password on Firebase using Javascript

**does the Firebase Java SDK have a reset password function too?**

4. user clicks on the link
5. user sets their new password

# Google Account

https://developers.google.com/api-client-library/java/google-oauth-java-client/oauth2

**Comment by Karim94** [comment]
Firebase provides a method to send an email to recover password.

**Comment by omarchehab98** [comment]
Added forgot password button to the login page.

![Screenshot of new login page](https://cloud.githubusercontent.com/assets/12089120/25319236/712443fc-2869-11e7-89db-496f6ec6ddfd.png)

059a45a3d53b9b91c26dee27b3cbb5900be7a5be

**Comment by omarchehab98** [comment]
[ ] Validate email field before attempting to send email
[ ] Prompt confirmation to reset password
